from tkinter import*
from tkinter.messagebox import*
root=Tk()
root.geometry('10000000x10000000')
img=PhotoImage(file='.\\Bus_for_project.png')
Label(root,image=img).grid(row=0,column=2,columnspan=10,padx=(1000//3))
Label(root,text="Online Bus Booking System",font='Cambria 20 bold',fg='red',bg='cyan2').grid(row=1,column=2,columnspan=10)
Label(root,text="Add Bus Details",font='Cambria 18 bold',fg='Dark green').grid(row=2,column=2,columnspan=10,pady=1000//55)
Label(root,text="Bus ID",font='Cambria 10').grid(row=3,column=0)
Entry(root).grid(row=3,column=1)
Label(root,text="bus Type",font='Cambia 10').grid(row=3,column=2)
bustype=StringVar()
opt=("2x2","ac2x2","3x2","ac3x2","ac sleeper 2x1","sleeper 2x1")
bustype.set("")
d_menu=OptionMenu(root,bustype,*opt).grid(row=3,column=3)
Label(root,text="Capacity",font='Cambria 10').grid(row=3,column=4)
Entry(root).grid(row=3,column=5)
Label(root,text="fareRS:",font='Cambria 10').grid(row=3,column=6)
Entry(root).grid(row=3,column=7)
Label(root,text="Operator id",font='Cambria 10').grid(row=3,column=8)
Entry(root).grid(row=3,column=9)
Label(root,text="Route id").grid(row=3,column=10)
Entry(root).grid(row=3,column=11)
def fun():
    showinfo('bus entry','bus record added')
def fun1():
    showinfo('bus entry','bus record successfully updated')
Button(root,text="Add Bus",font='Cambria 10',bg='lime green',command=fun).grid(row=4,column=6)
Button(root,text="Edit Bus",font='Cambria 10',bg='lime green',command=fun1).grid(row=4,column=7)
def close():
    root.destroy()
    import options.py
home=PhotoImage(file='.\\home.png')
Button(root,image=home,command=close).grid(row=4,column=9)
root.mainloop()
